"""add subscription.version for WS-event merge dedup

Revision ID: 5d3befc60c19
Revises: caac8150ed80
Create Date: 2026-05-22 18:43:16.570178

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5d3befc60c19"
down_revision: str | None = "caac8150ed80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("version", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "version")
    # ### end Alembic commands ###
