"""walls createdAt

Revision ID: 7c3779509867
Revises: 6196a903fd09
Create Date: 2024-12-25 19:14:26.920557

"""

import contextlib
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import inspect

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7c3779509867"
down_revision: str | None = "6196a903fd09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account_media") as batch_op:
        # Drop the old auto-generated foreign key constraint first
        with contextlib.suppress(Exception):
            batch_op.drop_constraint("account_media_accountId_fkey", type_="foreignkey")

        # Create new foreign key with explicit name and CASCADE
        batch_op.create_foreign_key(
            "fk_account_media_accountId_accounts",
            "accounts",
            ["accountId"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("media") as batch_op:
        # Keep the default as 0 since it's non-nullable
        batch_op.alter_column(
            "is_downloaded",
            existing_type=sa.INTEGER(),
            server_default=sa.text("0"),
            existing_nullable=False,
        )

    op.add_column(
        "walls", sa.Column("createdAt", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("walls", "createdAt")

    with op.batch_alter_table("media") as batch_op:
        batch_op.alter_column(
            "is_downloaded",
            existing_type=sa.INTEGER(),
            server_default=sa.text("0"),
            existing_nullable=False,
        )

    conn = op.get_bind()
    inspector = inspect(conn)
    am_fks = [fk["name"] for fk in inspector.get_foreign_keys("account_media")]

    with op.batch_alter_table("account_media") as batch_op:
        if "fk_account_media_accountId_accounts" in am_fks:
            batch_op.drop_constraint(
                "fk_account_media_accountId_accounts", type_="foreignkey"
            )
        batch_op.create_foreign_key(
            "fk_account_media_accountId_accounts", "accounts", ["accountId"], ["id"]
        )
    # ### end Alembic commands ###
