"""add monitorstate table

Revision ID: 7e027587c638
Revises: a91d60345484
Create Date: 2026-04-16 15:20:49.883533

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7e027587c638"
down_revision: str | None = "a91d60345484"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the monitor_state table for per-creator daemon persistence.

    Stores state that has no existing home in the identity map or other tables:
    - lastHasActiveStories: prior hasActiveStories value for flip detection
    - lastSeenAtAtLastRun: Account.lastSeenAt snapshot for skipping inactive creators
    - lastRunAt: timestamp of the last daemon processing cycle for this creator
    - updatedAt: row modification time set on every save
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitor_state",
        sa.Column("creatorId", sa.BigInteger(), nullable=False),
        sa.Column("lastHasActiveStories", sa.Boolean(), nullable=True),
        sa.Column("lastSeenAtAtLastRun", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lastRunAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["creatorId"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("creatorId"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the monitor_state table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("monitor_state")
    # ### end Alembic commands ###
