"""replace stories with media_stories

Revision ID: a91d60345484
Revises: f1a2b3c4d5e6
Create Date: 2026-04-15 16:53:26.734286

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a91d60345484"
down_revision: str | None = "f1a2b3c4d5e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_stories",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("accountId", sa.BigInteger(), nullable=False),
        sa.Column("contentType", sa.Integer(), nullable=True),
        sa.Column("contentId", sa.BigInteger(), nullable=True),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["accountId"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contentId"],
            ["account_media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_media_stories_accountId"), "media_stories", ["accountId"], unique=False
    )
    op.create_index(
        op.f("ix_media_stories_contentId"), "media_stories", ["contentId"], unique=False
    )
    op.drop_table("stories")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stories",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("authorId", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "createdAt",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["authorId"], ["accounts.id"], name=op.f("stories_authorId_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("stories_pkey")),
    )
    op.drop_index(op.f("ix_media_stories_contentId"), table_name="media_stories")
    op.drop_index(op.f("ix_media_stories_accountId"), table_name="media_stories")
    op.drop_table("media_stories")
    # ### end Alembic commands ###
