"""add subscriptions, subscription_plans, subscription_promos, follow_events tables

Revision ID: caac8150ed80
Revises: bb7006ec7c0e
Create Date: 2026-05-22 17:23:54.097266

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "caac8150ed80"
down_revision: str | None = "bb7006ec7c0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follow_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("accountId", sa.BigInteger(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("following_state", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accountId"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_follow_events_account_observed",
        "follow_events",
        ["accountId", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_follow_events_accountId"), "follow_events", ["accountId"], unique=False
    )
    op.create_table(
        "subscription_plans",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("accountId", sa.BigInteger(), nullable=False),
        sa.Column("subscriptionTierId", sa.BigInteger(), nullable=True),
        sa.Column("billingCycle", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("useAmounts", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accountId"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_plans_accountId"),
        "subscription_plans",
        ["accountId"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_plans_subscriptionTierId"),
        "subscription_plans",
        ["subscriptionTierId"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("accountId", sa.BigInteger(), nullable=False),
        sa.Column("subscriptionTierId", sa.BigInteger(), nullable=True),
        sa.Column("subscriptionTierName", sa.String(), nullable=True),
        sa.Column("subscriptionTierColor", sa.String(), nullable=True),
        sa.Column("planId", sa.BigInteger(), nullable=True),
        sa.Column("promoId", sa.String(), nullable=True),
        sa.Column("giftCodeId", sa.String(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("renewPrice", sa.Integer(), nullable=True),
        sa.Column("renewCorrelationId", sa.String(), nullable=True),
        sa.Column("autoRenew", sa.Integer(), nullable=True),
        sa.Column("billingCycle", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("renewDate", sa.DateTime(timezone=True), nullable=True),
        sa.Column("renewDatexD", sa.DateTime(timezone=True), nullable=True),
        sa.Column("createdAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("endsAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoPrice", sa.Integer(), nullable=True),
        sa.Column("promoDuration", sa.Integer(), nullable=True),
        sa.Column("promoStatus", sa.Integer(), nullable=True),
        sa.Column("promoStartsAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoEndsAt", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["accountId"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_accountId"), "subscriptions", ["accountId"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_endsAt"), "subscriptions", ["endsAt"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False
    )
    op.create_table(
        "subscription_promos",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("planId", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("maxUses", sa.Integer(), nullable=True),
        sa.Column("maxUsesBefore", sa.DateTime(timezone=True), nullable=True),
        sa.Column("newSubscribersOnly", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("startsAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("endsAt", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["planId"],
            ["subscription_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_promos_planId"),
        "subscription_promos",
        ["planId"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_subscription_promos_planId"), table_name="subscription_promos"
    )
    op.drop_table("subscription_promos")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_endsAt"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_accountId"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(
        op.f("ix_subscription_plans_subscriptionTierId"),
        table_name="subscription_plans",
    )
    op.drop_index(
        op.f("ix_subscription_plans_accountId"), table_name="subscription_plans"
    )
    op.drop_table("subscription_plans")
    op.drop_index(op.f("ix_follow_events_accountId"), table_name="follow_events")
    op.drop_index("idx_follow_events_account_observed", table_name="follow_events")
    op.drop_table("follow_events")
    # ### end Alembic commands ###
