"""Argument Parsing and Configuration Mapping"""

import argparse
from datetime import UTC, datetime
from functools import partial
from pathlib import Path
from typing import Any, get_args

from pydantic import BaseModel, SecretStr

from config.logging import set_debug_enabled, set_trace_enabled, textio_logger
from errors import ConfigError
from helpers.common import get_post_id_from_request, is_valid_post_id
from helpers.rich_progress import get_rich_console

from .config import parse_items_from_line, sanitize_creator_names
from .fanslyconfig import FanslyConfig
from .modes import DownloadMode
from .schema import (
    CacheSection,
    ConfigSchema,
    LoggingSection,
    LogicSection,
    MonitoringSection,
    MyAccountSection,
    OptionsSection,
    PostgresSection,
    StashContextSection,
    TargetedCreatorSection,
)


_GENERATE_CONFIG_HEADER = """\
# fansly-scraper / fansly-downloader-ng — config.yaml scaffold
#
# This file was generated by ``--generate-config``. Only the
# operator-required slots (always-rendered fields) are present. Every
# other knob has a working default; add it here to override.
#
# Full configuration reference:
#   https://jakan-kink.github.io/fansly-scraper/
#   docs/configuration/config_options.md (in this repo)
"""


def handle_generate_config(path: str) -> None:
    """Write a minimal scaffold config.yaml and return.

    Builds a fresh ConfigSchema (every section + field at default) and
    dumps via the schema's standard dump path — which means the cascade-up
    rule + always-marker filter automatically reduce the output to the
    minimum required slots. Operators see exactly the keys they must edit
    and nothing else.

    Refuses to overwrite an existing file: the whole point of this command
    is bootstrapping, not migration. Existing configs go through the
    INI-to-YAML migrator or are hand-edited.
    """
    target = Path(path)
    if target.exists():
        textio_logger.opt(depth=1).log(
            "ERROR",
            f"--generate-config: {target} already exists. Refusing to overwrite. "
            f"Move or rename it first, or pass a different path.",
        )
        raise SystemExit(1)

    schema = ConfigSchema()
    schema.dump_yaml(target)

    body = target.read_text(encoding="utf-8")
    target.write_text(_GENERATE_CONFIG_HEADER + "\n" + body, encoding="utf-8")
    textio_logger.opt(depth=1).log(
        "INFO",
        f"Wrote scaffold config to {target}. Edit ``authorization_token``, "
        f"``user_agent``, ``usernames``, and ``download_directory``, then run "
        f"the program normally.",
    )


_SHOW_CONFIG_SECTIONS: list[tuple[str, type[BaseModel]]] = [
    ("targeted_creator", TargetedCreatorSection),
    ("my_account", MyAccountSection),
    ("options", OptionsSection),
    ("postgres", PostgresSection),
    ("logging", LoggingSection),
    ("cache", CacheSection),
    ("monitoring", MonitoringSection),
    ("logic", LogicSection),
    ("stash_context", StashContextSection),
]


def _is_blank_eligible(annotation: Any) -> bool:
    """True iff the field's type annotation includes ``None`` (X | None / Optional[X])."""
    return type(None) in get_args(annotation)


def _format_field_value(value: Any, *, blank_eligible: bool) -> str:
    """Render a field's value for ``--show-config`` output.

    Rules:
      - ``None`` on a blank-eligible (``X | None``) field → empty string
        (matches user spec: "blank for those that can be blank").
      - ``SecretStr`` → ``str(value)`` which is masked (``**********``)
        per Pydantic's safety default. Auth path uses ``get_secret_value()``
        directly; this masking is display-only — to verify the actual stored
        value, open ``config.yaml``.
      - Lists render with brackets; everything else falls through to ``str()``.
    """
    if value is None and blank_eligible:
        return ""
    if isinstance(value, SecretStr):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(str(item) for item in value) + "]"
    return str(value)


def handle_show_config(config: FanslyConfig) -> None:
    """Render the loaded configuration to the global Rich console.

    Walks every section + every field — including Optional sections that
    are absent from YAML and conditional fields at default — so the
    operator sees the full menu (per "ALL ALL"). Bold marks operator-set
    values (``model_fields_set``); dim text marks defaults; an empty
    string after the colon marks blank-eligible (``X | None``) fields
    with ``None`` value. Secrets are always masked — open ``config.yaml``
    directly to verify their stored values.
    """
    schema: ConfigSchema = config._schema or ConfigSchema()
    console = get_rich_console()

    for section_name, section_class in _SHOW_CONFIG_SECTIONS:
        section = getattr(schema, section_name)
        # ALL ALL: even if an Optional section is None at runtime, walk its
        # type's defaults so the operator sees every field they could set.
        if section is None:
            section = section_class()
        fields_set = section.model_fields_set
        console.print(f"[bold cyan]{section_name}:[/bold cyan]")
        for field_name, field_info in section.__class__.model_fields.items():
            value = getattr(section, field_name)
            blank = _is_blank_eligible(field_info.annotation)
            value_str = _format_field_value(value, blank_eligible=blank)
            # Resolve serialization alias for display
            # (LoggingSection.json_level → "json")
            display_key = (
                field_info.serialization_alias
                if field_info.serialization_alias
                else field_name
            )
            if field_name in fields_set:
                console.print(
                    f"  [bold]{display_key}:[/bold] [bold green]{value_str}[/bold green]"
                )
            else:
                console.print(f"  [dim]{display_key}:[/dim] {value_str}")


def _parse_iso_datetime(value: str) -> datetime:
    """Parse an ISO 8601 timestamp string into a timezone-aware datetime.

    Accepts formats like ``2026-01-01T00:00:00Z`` or ``2026-01-01T00:00:00+00:00``.
    Naive timestamps (no timezone) are rejected to avoid ambiguous comparisons.

    :param str value: The ISO 8601 timestamp string to parse.
    :return: A timezone-aware :class:`datetime` object.
    :raises argparse.ArgumentTypeError: If the string cannot be parsed or is naive.
    """
    try:
        # Python 3.11+ fromisoformat handles Z suffix natively
        dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        raise argparse.ArgumentTypeError(
            f"Invalid ISO 8601 timestamp: {value!r}. "
            "Expected format: 2026-01-01T00:00:00Z or 2026-01-01T00:00:00+00:00"
        )
    if dt.tzinfo is None:
        raise argparse.ArgumentTypeError(
            f"Timestamp {value!r} has no timezone. Use UTC suffix Z or +00:00."
        )
    return dt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fansly Downloader NG scrapes media content from one or more Fansly creators. "
        "Settings will be taken from config.ini or internal defaults and "
        "can be overriden with the following parameters.\n"
        "Using the command-line will not overwrite config.ini.",
    )

    # region Essential Options

    parser.add_argument(
        "-uf",
        "--use-following",
        action="store_true",
        default=False,
        help="Process following list instead of targeted creators",
        required=False,
    )

    parser.add_argument(
        "-ufp",
        "--use-following-with-pagination",
        action="store_true",
        default=False,
        help="Process following list with pagination duplication enabled",
        required=False,
    )

    parser.add_argument(
        "-r",
        "--reverse-order",
        action="store_true",
        default=False,
        help="Process creators in reverse order (applies to following list and targeted creators)",
        required=False,
    )

    parser.add_argument(
        "-u",
        "--user",
        required=False,
        default=None,
        metavar="USER",
        dest="users",
        help="A list of one or more Fansly creators you want to download "
        "content from.\n"
        "This overrides TargetedCreator > username in config.ini.",
        nargs="+",
    )
    parser.add_argument(
        "-dir",
        "--directory",
        required=False,
        default=None,
        dest="download_directory",
        help="The base directory to store all creators' content in. "
        "A subdirectory for each creator will be created automatically. "
        "If you do not specify --no-folder-suffix, "
        "each creator's folder will be suffixed with "
        "_fansly"
        ". "
        "Please remember to quote paths including spaces.",
    )
    parser.add_argument(
        "-t",
        "--token",
        required=False,
        default=None,
        metavar="AUTHORIZATION_TOKEN",
        dest="token",
        help="The Fansly authorization token obtained from a browser session.",
    )
    parser.add_argument(
        "-ua",
        "--user-agent",
        required=False,
        default=None,
        dest="user_agent",
        help="The browser user agent string to use when communicating with "
        "Fansly servers. This should ideally be set to the user agent "
        "of the browser you use to view Fansly pages and where the "
        "authorization token was obtained from.",
    )
    parser.add_argument(
        "-ck",
        "--check-key",
        required=False,
        default=None,
        dest="check_key",
        help="Fansly's _checkKey in the main.js on https://fansly.com. "
        "Essential for digital signature and preventing bans.",
    )

    # endregion Essentials

    # region Download modes

    download_modes = parser.add_mutually_exclusive_group(required=False)

    download_modes.add_argument(
        "--normal",
        required=False,
        default=False,
        action="store_true",
        dest="download_mode_normal",
        help='Use "Normal" download mode. This will download messages and timeline media.',
    )
    download_modes.add_argument(
        "--messages",
        required=False,
        default=False,
        action="store_true",
        dest="download_mode_messages",
        help='Use "Messages" download mode. This will download messages only.',
    )
    download_modes.add_argument(
        "--timeline",
        required=False,
        default=False,
        action="store_true",
        dest="download_mode_timeline",
        help='Use "Timeline" download mode. This will download timeline content only.',
    )
    download_modes.add_argument(
        "--collection",
        required=False,
        default=False,
        action="store_true",
        dest="download_mode_collection",
        help='Use "Collection" download mode. This will ony download a collection.',
    )
    download_modes.add_argument(
        "--single",
        required=False,
        default=None,
        metavar="REQUESTED_POST",
        dest="download_mode_single",
        help='Use "Single" download mode. This will download a single post '
        "by link or ID from an arbitrary creator. "
        "A post ID must be at least 10 characters and consist of digits only."
        "Example - https://fansly.com/post/1283998432982 -> ID is: 1283998432982",
    )

    # endregion Download Modes

    # region Other Options

    parser.add_argument(
        "-ni",
        "--non-interactive",
        required=False,
        default=False,
        action="store_true",
        dest="non_interactive",
        help="Do not ask for input during warnings and errors that need "
        "your attention but can be automatically continued. "
        "Setting this will download all media of all users without any "
        "intervention.",
    )
    parser.add_argument(
        "-npox",
        "--no-prompt-on-exit",
        required=False,
        default=False,
        action="store_true",
        dest="no_prompt_on_exit",
        help="Do not ask to press <ENTER> at the very end of the program. "
        "Set this for a fully automated/headless experience.",
    )
    parser.add_argument(
        "-nfs",
        "--no-folder-suffix",
        required=False,
        default=False,
        action="store_true",
        dest="no_folder_suffix",
        help='Do not add "_fansly" to the download folder of a creator.',
    )
    parser.add_argument(
        "-np",
        "--no-previews",
        required=False,
        default=False,
        action="store_true",
        dest="no_media_previews",
        help="Do not download media previews (which may contain spam).",
    )
    parser.add_argument(
        "-hd",
        "--hide-downloads",
        required=False,
        default=False,
        action="store_true",
        dest="hide_downloads",
        help="Do not show download information.",
    )
    parser.add_argument(
        "-hsd",
        "--hide-skipped-downloads",
        required=False,
        default=False,
        action="store_true",
        dest="hide_skipped_downloads",
        help="Do not show download information for skipped files.",
    )
    parser.add_argument(
        "-nof",
        "--no-open-folder",
        required=False,
        default=False,
        action="store_true",
        dest="no_open_folder",
        help="Do not open the download folder on creator completion.",
    )
    parser.add_argument(
        "-nsm",
        "--no-separate-messages",
        required=False,
        default=False,
        action="store_true",
        dest="no_separate_messages",
        help="Do not separate messages into their own folder.",
    )
    parser.add_argument(
        "-nst",
        "--no-separate-timeline",
        required=False,
        default=False,
        action="store_true",
        dest="no_separate_timeline",
        help="Do not separate timeline content into it's own folder.",
    )
    parser.add_argument(
        "-sp",
        "--separate-previews",
        required=False,
        default=False,
        action="store_true",
        dest="separate_previews",
        help="Separate preview media (which may contain spam) into their own folder.",
    )
    parser.add_argument(
        "-udt",
        "--use-duplicate-threshold",
        required=False,
        default=False,
        action="store_true",
        dest="use_duplicate_threshold",
        help="Use an internal de-deduplication threshold to not download "
        "already downloaded media again.",
    )
    parser.add_argument(
        "-upd",
        "--use-pagination-duplication",
        required=False,
        default=False,
        action="store_true",
        dest="use_pagination_duplication",
        help="Check each page for duplicates during pagination.",
    )
    parser.add_argument(
        "-tr",
        "--timeline-retries",
        required=False,
        default=None,
        type=int,
        dest="timeline_retries",
        help="Number of retries on empty timelines. Defaults to 1. "
        "Part of anti-rate-limiting measures - try bumping up to eg. 2 "
        "if nothing gets downloaded. Also see the explanation of "
        "--timeline-delay-seconds.",
    )
    parser.add_argument(
        "-td",
        "--timeline-delay-seconds",
        required=False,
        default=None,
        type=int,
        dest="timeline_delay_seconds",
        help="Number of seconds to wait before retrying empty timelines. "
        "Defaults to 60. "
        "Part of anti-rate-limiting measures - 1 retry/60 seconds works "
        "all the time but also unnecessarily delays at the proper end of "
        "a creator's timeline - since reaching the end and being "
        "rate-limited is indistinguishable as of now. "
        "You may try to lower this or set to 0 in order to speed things "
        "up - but if nothing gets downloaded the Fansly server firewalls "
        "rate-limited you. "
        "You can calculate yourself how long a download session "
        "(without download time and extra retries) will last at minimum: "
        "NUMBER_OF_CREATORS * TIMELINE_RETRIES * TIMELINE_DELAY_SECONDS",
    )
    parser.add_argument(
        "-ar",
        "--api-max-retries",
        required=False,
        default=None,
        type=int,
        dest="api_max_retries",
        help="Maximum number of retries for API requests that fail with 429 (rate limit). "
        "Defaults to 10. "
        "Higher values allow exponential backoff to reach maximum backoff time "
        "(30s → 60s → 120s → 240s → 300s max) before giving up. "
        "Lower values may cause downloads to fail during sustained rate limiting.",
    )

    # PostgreSQL arguments
    parser.add_argument(
        "--pg-host",
        required=False,
        default=None,
        type=str,
        dest="pg_host",
        help="PostgreSQL host (default: localhost)",
    )
    parser.add_argument(
        "--pg-port",
        required=False,
        default=None,
        type=int,
        dest="pg_port",
        help="PostgreSQL port (default: 5432)",
    )
    parser.add_argument(
        "--pg-database",
        required=False,
        default=None,
        type=str,
        dest="pg_database",
        help="PostgreSQL database name (default: fansly_metadata)",
    )
    parser.add_argument(
        "--pg-user",
        required=False,
        default=None,
        type=str,
        dest="pg_user",
        help="PostgreSQL username (default: fansly_user)",
    )
    parser.add_argument(
        "--pg-password",
        required=False,
        default=None,
        type=str,
        dest="pg_password",
        help="PostgreSQL password (prefer FANSLY_PG_PASSWORD environment variable)",
    )
    parser.add_argument(
        "--temp-folder",
        required=False,
        default=None,
        type=str,
        dest="temp_folder",
        help="Custom path for temporary files. "
        "If not specified, uses system default temp folder.",
    )
    parser.add_argument(
        "--stash-only",
        required=False,
        default=False,
        action="store_true",
        dest="stash_only",
        help="Only process Stash metadata, skip downloading media.",
    )

    # endregion Other Options

    # region Monitoring arguments

    monitoring_group = parser.add_argument_group(
        "Monitoring",
        "Options for the monitoring daemon and per-run baseline overrides.",
    )
    monitoring_exclusive = monitoring_group.add_mutually_exclusive_group()

    monitoring_exclusive.add_argument(
        "--monitor-since",
        required=False,
        default=None,
        type=_parse_iso_datetime,
        dest="monitor_since",
        metavar="ISO_TIMESTAMP",
        help="Override each creator's stored lastCheckedAt with this UTC timestamp "
        "for the current run only. Useful to re-check all creators from a given "
        "point in time without modifying stored state. "
        "Example: --monitor-since 2026-01-01T00:00:00Z",
    )
    monitoring_exclusive.add_argument(
        "--full-pass",
        required=False,
        default=False,
        action="store_true",
        dest="full_pass",
        help="Force a full re-check of every creator by setting the session baseline "
        "to 2000-01-01T00:00:00Z. Equivalent to --monitor-since 2000-01-01T00:00:00Z. "
        "Useful when you want to re-download or re-verify all content.",
    )

    monitoring_group.add_argument(
        "-d",
        "--daemon",
        "--monitor",
        required=False,
        default=False,
        action="store_true",
        dest="daemon_mode",
        help=(
            "After the batch download completes, enter the post-batch monitoring "
            "daemon (WebSocket listener + timeline/story polling loop) and continue "
            "archiving new content until interrupted. Equivalent to setting "
            "monitoring.daemon_mode = true in config.yaml."
        ),
    )

    # endregion Monitoring

    # region Developer/troubleshooting arguments

    parser.add_argument(
        "-v",
        "--verbose",
        required=False,
        default=0,
        action="count",
        dest="verbose",
        help="Increase log verbosity. -v overrides every handler to DEBUG; "
        "-vv overrides every handler to TRACE and opens the trace.log file "
        "sink. Repeatable; runtime-only, never written back to config.yaml.",
    )
    parser.add_argument(
        "--generate-config",
        required=False,
        default=None,
        nargs="?",
        const="config.yaml",
        metavar="PATH",
        dest="generate_config",
        help="Write a minimal scaffold config.yaml containing only the "
        "operator-required fields (always-rendered slots) and exit. "
        "Optional PATH defaults to ./config.yaml. See "
        "https://jakan-kink.github.io/fansly-scraper/ for the full reference.",
    )
    parser.add_argument(
        "--show-config",
        required=False,
        default=False,
        action="store_true",
        dest="show_config",
        help="Print the loaded configuration (all sections, all fields) and "
        "exit. Operator-set fields are bold, defaults are normal, "
        "blank-eligible Optional fields render as empty after the colon. "
        "Secrets are always masked — open config.yaml directly to verify "
        "their actual stored values.",
    )
    # endregion Dev/Tshoot

    return parser.parse_args()


def check_attributes(
    args: argparse.Namespace,
    config: FanslyConfig,
    arg_attribute: str,
    config_attribute: str,
) -> None:
    """A helper method to validate the presence of attributes (properties)
    in `argparse.Namespace` and `FanslyConfig` objects for mapping
    arguments. This is to locate code changes and typos.

    :param args: The arguments parsed.
    :type args: argparse.Namespace
    :param config: The Fansly Downloader NG configuration.
    :type config: FanslyConfig
    :param arg_attribute: The argument destination variable name.
    :type arg_attribute: str
    :param config_attribute: The configuration attribute/property name.
    :type config_attribute: str

    :raise RuntimeError: Raised when an attribute does not exist.
    """
    if hasattr(args, arg_attribute) and hasattr(config, config_attribute):
        return

    raise RuntimeError(
        "Internal argument configuration error - please contact the developer."
        f"(args.{arg_attribute} == {hasattr(args, arg_attribute)}, "
        f"config.{config_attribute} == {hasattr(config, config_attribute)})"
    )


def _handle_verbosity_settings(args: argparse.Namespace, config: FanslyConfig) -> None:
    """Apply ``-v`` / ``-vv`` to the runtime debug/trace flags.

    Cumulative: ``-v`` → debug, ``-vv`` → debug + trace. Both flags are
    runtime-only — marked ephemeral so they never write back to config.yaml.
    Operators wanting persistent verbosity edit ``logging.global.default_level``
    instead.
    """
    if args.verbose >= 1:
        config.debug = True
        config._ephemeral_overrides.add("debug")
    if args.verbose >= 2:
        config.trace = True
        config._ephemeral_overrides.add("trace")
    set_debug_enabled(config.debug)
    set_trace_enabled(config.trace)

    if config.debug:
        textio_logger.opt(depth=1).log("DEBUG", f"Args: {args}")


def _handle_user_settings(args: argparse.Namespace, config: FanslyConfig) -> bool:
    """Handle user settings and return if config was overridden."""
    config_overridden = False

    # Handle use_following_with_pagination (combined option)
    if args.use_following_with_pagination:
        config.use_following = True
        config.use_pagination_duplication = True
        # CLI flags are per-run; keep YAML's persisted values untouched.
        config._ephemeral_overrides.add("use_following")
        config._ephemeral_overrides.add("use_pagination_duplication")
        # ``-uf``/``-ufp`` causes the daemon's ``_refresh_following`` to fetch
        # the live following list and overwrite ``config.user_names``. Without
        # this preemptive ephemeral mark, the next ``_save_config`` would
        # write the API-fetched list to YAML and silently clobber the user's
        # curated ``usernames:`` list. Mark ``user_names`` ephemeral so any
        # runtime mutation stays runtime-only.
        config._ephemeral_overrides.add("user_names")
        config_overridden = True
        # If this combined option is used, we don't need to check the individual options
        return config_overridden

    # Check for conflicting arguments
    if args.use_following and args.users is not None:
        raise ConfigError(
            "Cannot use both --use-following and --user options at the same time. "
            "Please use either --use-following to process your following list, "
            "or --user to specify target creators."
        )

    # Handle use_following
    if args.use_following:
        config.use_following = True
        config._ephemeral_overrides.add("use_following")
        # Same rationale as -ufp above: protect curated user_names from being
        # overwritten by the auto-fetched following list during a daemon run.
        config._ephemeral_overrides.add("user_names")
        config_overridden = True

    if args.users is None:
        return config_overridden

    users_line = " ".join(args.users)
    config.user_names = sanitize_creator_names(parse_items_from_line(users_line))
    # ``-u`` is a per-run targeting override; the persisted creator list in
    # YAML stays as the user authored it.
    config._ephemeral_overrides.add("user_names")
    config_overridden = True

    if config.debug:
        textio_logger.opt(depth=1).log(
            "DEBUG", f"Value of `args.users` is: {args.users}"
        )
        textio_logger.opt(depth=1).log(
            "DEBUG", f"`args.users` is None == {args.users is None}"
        )
        textio_logger.opt(depth=1).log(
            "DEBUG", f"`config.username` is: {config.user_names}"
        )

    return config_overridden


def _handle_download_mode(
    args: argparse.Namespace, config: FanslyConfig
) -> tuple[bool, bool]:
    """Handle download mode settings and return (config_overridden, download_mode_set)."""
    config_overridden = False
    download_mode_set = False

    # Map of argument flags to download modes
    mode_map = {
        "stash_only": DownloadMode.STASH_ONLY,
        "download_mode_normal": DownloadMode.NORMAL,
        "download_mode_messages": DownloadMode.MESSAGES,
        "download_mode_timeline": DownloadMode.TIMELINE,
        "download_mode_collection": DownloadMode.COLLECTION,
    }

    # Check each mode flag
    for arg_name, mode in mode_map.items():
        if getattr(args, arg_name, False):
            config.download_mode = mode
            config._ephemeral_overrides.add("download_mode")
            return True, True

    # Handle single mode separately due to additional validation
    if args.download_mode_single is not None:
        post_id = get_post_id_from_request(args.download_mode_single)
        if not is_valid_post_id(post_id):
            raise ConfigError(
                f"Argument error - '{post_id}' is not a valid post ID. "
                "For an ID at least 10 characters/only digits are required."
            )
        config.download_mode = DownloadMode.SINGLE
        config.post_id = post_id
        config._ephemeral_overrides.add("download_mode")
        return True, True

    return config_overridden, download_mode_set


def _handle_path_settings(
    args: argparse.Namespace, config: FanslyConfig, attr_name: str
) -> bool:
    """Handle path-type settings and return if config was overridden."""
    arg_attribute = getattr(args, attr_name)
    if arg_attribute is None:
        return False

    if attr_name == "temp_folder":
        if arg_attribute:  # Only set if not empty string
            setattr(config, attr_name, Path(arg_attribute))
        else:
            setattr(config, attr_name, None)
    elif attr_name == "download_directory":
        setattr(config, attr_name, Path(arg_attribute))
    else:
        setattr(config, attr_name, arg_attribute)

    return True


def _handle_not_none_settings(args: argparse.Namespace, config: FanslyConfig) -> bool:
    """Handle settings that should be set when not None."""
    check_attr = partial(check_attributes, args, config)
    config_overridden = False

    not_none_settings = [
        "download_directory",
        "token",
        "user_agent",
        "check_key",
        "temp_folder",
        # PostgreSQL settings
        "pg_host",
        "pg_port",
        "pg_database",
        "pg_user",
        "pg_password",
    ]

    for attr_name in not_none_settings:
        check_attr(attr_name, attr_name)
        if _handle_path_settings(args, config, attr_name):
            config_overridden = True

    return config_overridden


def _handle_boolean_settings(args: argparse.Namespace, config: FanslyConfig) -> bool:
    """Handle boolean settings and return if config was overridden."""
    check_attr = partial(check_attributes, args, config)
    config_overridden = False

    # Handle positive boolean flags
    positive_bools = [
        "separate_previews",
        "use_duplicate_threshold",
        "use_pagination_duplication",
        "reverse_order",
    ]

    # ``reverse_order`` is runtime-only (not in OptionsSection schema) so it
    # cannot leak to YAML; the rest are persisted and need ephemeral marking
    # when set via CLI so per-run flags don't pin a new YAML default.
    for attr_name in positive_bools:
        check_attr(attr_name, attr_name)
        arg_attribute = getattr(args, attr_name)
        if arg_attribute is True:
            setattr(config, attr_name, arg_attribute)
            if attr_name != "reverse_order":
                config._ephemeral_overrides.add(attr_name)
            config_overridden = True

    # Handle negative boolean flags
    negative_bool_map = [
        ("non_interactive", "interactive"),
        ("no_prompt_on_exit", "prompt_on_exit"),
        ("no_folder_suffix", "use_folder_suffix"),
        ("no_media_previews", "download_media_previews"),
        ("hide_downloads", "show_downloads"),
        ("hide_skipped_downloads", "show_skipped_downloads"),
        ("no_open_folder", "open_folder_when_finished"),
        ("no_separate_messages", "separate_messages"),
        ("no_separate_timeline", "separate_timeline"),
    ]

    for arg_name, config_name in negative_bool_map:
        check_attr(arg_name, config_name)
        arg_attribute = getattr(args, arg_name)
        if arg_attribute is True:
            setattr(config, config_name, not arg_attribute)
            # Per-run override; YAML's persisted default stays intact.
            config._ephemeral_overrides.add(config_name)
            config_overridden = True

    return config_overridden


def _handle_unsigned_ints(args: argparse.Namespace, config: FanslyConfig) -> bool:
    """Handle unsigned integer settings and return if config was overridden."""
    check_attr = partial(check_attributes, args, config)
    config_overridden = False

    unsigned_ints = [
        "timeline_retries",
        "timeline_delay_seconds",
        "api_max_retries",
    ]

    for attr_name in unsigned_ints:
        check_attr(attr_name, attr_name)
        arg_attribute = getattr(args, attr_name)

        if arg_attribute is None:
            continue

        try:
            int_value = max(0, int(arg_attribute))
            config_attribute = getattr(config, attr_name)
            if int_value != int(config_attribute):
                setattr(config, attr_name, int_value)
                config_overridden = True
        except ValueError:
            pass

    return config_overridden


def _handle_monitoring_settings(args: argparse.Namespace, config: FanslyConfig) -> bool:
    """Handle monitoring session baseline and daemon-mode flags.

    ``--monitor-since`` sets the session baseline to the given datetime.
    ``--full-pass`` sets the session baseline to 2000-01-01T00:00:00 UTC, which
    effectively forces a fresh pass for every creator regardless of stored state.
    ``--daemon`` / ``-d`` / ``--monitor`` sets daemon_mode to True.
    CLI takes precedence over any value already loaded from config.yaml.
    """
    overridden = False
    baseline: datetime | None = None

    if getattr(args, "full_pass", False):
        baseline = datetime(2000, 1, 1, tzinfo=UTC)
    elif getattr(args, "monitor_since", None) is not None:
        baseline = args.monitor_since

    if baseline is not None:
        # Runtime-only: the daemon consumes ``monitoring_session_baseline``
        # once per creator (see daemon/runner.py:_process_timeline_candidate
        # ``baseline_consumed`` set), and ``mark_creator_processed`` advances
        # ``MonitorState.lastCheckedAt`` in the database after each successful
        # download. The CLI baseline self-extinguishes within the run; writing
        # it into the YAML schema would silently turn ``--full-pass`` into a
        # permanent setting that re-fires on every subsequent invocation.
        # YAML-authored ``session_baseline`` is supported as a one-shot
        # directive by the load-time consume-and-reset logic in
        # ``config/config.py::_populate_config_from_schema``.
        config.monitoring_session_baseline = baseline
        overridden = True

    if getattr(args, "daemon_mode", False):
        config.daemon_mode = True
        config.interactive = False
        overridden = True

    return overridden


def map_args_to_config(args: argparse.Namespace, config: FanslyConfig) -> bool:
    """Maps command-line arguments to the configuration object of
    the current session.

    :param argparse.Namespace args: The command-line arguments
        retrieved via argparse.
    :param FanslyConfig config: The program configuration to map the
        arguments to.

    :return bool download_mode_set: Used to determine whether the
        download mode has been specified with the command line.
    """
    if config.config_path is None:
        raise RuntimeError(
            "Internal error mapping arguments - configuration path not set. Load the config first."
        )

    download_mode_set = False

    # Handle each group of settings
    _handle_verbosity_settings(args, config)
    _handle_user_settings(args, config)

    _, mode_set = _handle_download_mode(args, config)
    if mode_set:
        download_mode_set = True

    _handle_not_none_settings(args, config)
    _handle_boolean_settings(args, config)
    _handle_unsigned_ints(args, config)
    _handle_monitoring_settings(args, config)

    return download_mode_set
